POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "Smartphone",
  "price": 1299.99
}


###
# GET /products
GET http://localhost:8000/products/7295524c-9a02-40ec-9332-7da34c9f253d
