POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "Smartphone",
  "price": 1299.99
}

###
# GET /products
GET http://localhost:8000/products/7295524c-9a02-40ec-9332-7da34c9f253d

###
# PUT /products/{id} + body
PUT http://localhost:8000/products/af9ae15b-13ee-4303-a00d-f0c55f469902
Content-Type: application/json

{
  "name": "Macbook Pro",
  "price": 7999.99
}
