// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/brunoliveiradev/GoExpertPostGrad/wire/product"
	"github.com/google/wire"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func NewProductUseCase(db *sql.DB) *product.ProductUseCase {
	repository := product.NewProductRepository(db)
	productUseCase := product.NewProductUseCase(repository)
	return productUseCase
}

// wire.go:

var setRepoDependency = wire.NewSet(product.NewProductRepository, wire.Bind(new(product.ProductRepositoryInterface), new(*product.Repository)))
